<?php


namespace Nassau\Silex\HttpKernel;


use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;

class TemplateResponse extends Response
{
	/**
	 * @var string
	 */
	private $template;
	/**
	 * @var array
	 */
	private $context;

	public function __construct($template, $context = [], $status = 200, $headers = array())
	{
		parent::__construct("", $status, $headers); // TODO: Change the autogenerated stub
		$this->template = $template;
		$this->context = $context;
	}

	public function render(\Twig_Environment $twig)
	{
		$this->setContent($twig->render($this->template, $this->context));
	}

}